- name: Gather facts on the AWS VPC using the Tag 'Name'
  ec2_vpc_net_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ aws_vpc.name }}"
  register: vpc_info

- name: Create vpc facts
  set_fact:
    vpc: "{{ vpc_info.vpcs[0] }}"
  when: vpc_info is defined and vpc_info.vpcs is defined and vpc_info.vpcs | length > 0