---
- name: Install the Required Libraries
  yum:
    name: "{{ item.name }}"
    state: present
    use_backend: "{{ yum_backend }}"
  with_items: "{{ yum_installs }}"

- name: Install Firewalld Service
  yum:
    name: firewalld
    state: present

- name:  Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open Ports for Nexus
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items: "{{ open_nexus_ports }}"

- name: Make sure the Nexus tar file does not exist
  file:
    path: "{{ role_path }}/files/nexus_software/nexus-3.28.0-01-unix.tar.gz"
    state: absent
  delegate_to: 127.0.0.1
  run_once: true

- name: Combine the Nexus software into tar file.  Was split to be put into git.
  shell: 'cat {{ role_path }}/files/nexus_software/nexus-3.28.0-01-unix.tar.gz.parta* > {{ role_path }}/files/nexus_software/nexus-3.28.0-01-unix.tar.gz'
  delegate_to: 127.0.0.1
  run_once: true

- name: Get sha1sum of file
  stat:
    path: "{{ role_path }}/files/nexus_software/nexus-3.28.0-01-unix.tar.gz"
    checksum_algorithm: sha1
    get_checksum: yes
  register: sha
  delegate_to: 127.0.0.1
  run_once: true

- name: Fail if the original Nexus software checksum is different from the original file.
  fail:
    msg:  "The Nexus software tar file does not have the same sha1 checksum as the original."
  delegate_to: 127.0.0.1
  run_once: true
  when: nexus_software_sha1_checksum != sha.stat.checksum
