---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Include the variables needed for creation
      include_vars:
        file: "vars/main.yml"

    # Developer must implement.

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | default(false) | bool

    - name: Query a VPC with dedicated tenancy and a couple of tags
      ec2_vpc_net:
        name: vpc_openshift_idm
        cidr_block: 10.10.0.0/16
        dns_support: yes
        dns_hostnames: yes
        tags:
          module: "Openshift Cluster VPC"
        tenancy: default
        state: present
      register: ec2_vpc_net

    - name: Set the VPC Fact
      set_fact:
        vpc: "{{ ec2_vpc_net.vpc }}"

    - name: Query the ec2 vpc subnet
    # query the subnet for the vpc with a cidr block
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.id }}"
        state: present
        cidr: "10.10.0.0/24"
        # enable public ip
        map_public: yes
        state: present
        resource_tags:
          Name: "openshift_subnet"
      register: subnet_result

    - name: Set the VPC Subnet Fact
      set_fact:
        vpc_subnet: "{{ subnet_result['subnet'] }}"


    - name: Gather EC2 Instance Facts
      ec2_instance_facts:
      register: ec2_info

    - name: Print info
      debug:
        var: ec2_info


    - name: terminate
      ec2:
        instance_ids: "{{ item.instance_id }}"
        state: absent
        wait: yes
      with_items: "{{ ec2_info.instances }}"
      when: item.state.name != 'terminated' and item.tags.Name == aws_idm_instance_name

