- name: Register variable for open ports
  command: firewall-cmd --list-ports
  register: open_ports

- name: Fail if an Nexus Port is Closed
  fail:
    msg: "The port '{{ item }}' is not open."
  with_items: "{{ open_nexus_ports }}"
  when: "'{{ item }}' not in open_ports.stdout"