- name: Get EC2 instance information
  ec2_instance_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ current_ec2_instance }}"
  register: ec2_info

- name: Register failure count
  set_fact:
    ec2_instances_not_created: "{{ ec2_instances_not_created + [current_ec2_instance] }}"
  when: ec2_info.instances is not defined or ec2_info.instances | length == 0