---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Include the module vars file.
      include_vars:
        file: ../../defaults/main.yml

    - name:  Determine if vpc exists
      include_tasks: tasks/check-for-vpc-existence.yml

    - name:  Determine if vpc exists
      include_tasks: tasks/check-for-vpc-subnet-existence.yml

    - name:  Determine if vpc exists
      include_tasks: tasks/check-for-vpc-gateway-existence.yml

    # Gather information about any VPC route table with a tag key Name and value Example
    - name: Create the EC2 Route Table Information
      ec2_vpc_route_table_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        filters:
          "tag:Name": Example


