---
# tasks file for idm-install

- name: Install Firewalld Service
  yum:
    name: firewalld
    state: present

- name: Start Firewalld Service
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open Ports for IDM
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items: "{{ open_idm_ports }}"

- name: Enable IDM module
  shell:
    cmd: dnf module enable -y idm:DL1

- name: Install the Latest Version of IDM.  Please wait this could take a couple of minutes....
  dnf:
    name: ['ipa-server', 'ipa-server-dns']
    state: latest