- name: Check if the AWS Keys are present.
  include_tasks: "{{ role_path }}/tasks/verify/check-if-the-aws-keys-are-present.yml"

- name: Check if the AWS VPC is present.
  include_tasks: "{{ role_path }}/tasks/verify/check-if-vpc-is-present.yml"

- name: Force a failure by naming a non-existent VPC subnet
  set_fact:
    aws_vpc: "{{ aws_vpc|default({}) | combine( { 'subnets':  { 'control': { 'name': 'fake_subnet_name' } } } ) }}"

- name: Gather facts on the AWS Control Subnet
  ec2_vpc_subnet_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ aws_vpc.subnets.control.name }}"
  register: vpc_control_subnet_info


- name: Print the vpc control subnet info
  debug:
    var: vpc_control_subnet_info

- name: Fail if the control subnet does not exist
  fail:
    msg:  "The subnet called '{{ aws_vpc.subnets.control.name  }}' does not exist."
  when:
    - vpc_control_subnet_info.subnets is defined
    - vpc_control_subnet_info.subnets | length  == 0

