- name: Change the DNS to IDM Server
  command: "{{ item }}"
  with_items:
    - 'nmcli conn modify "{{ idm_nmcli_interface_name }}" ipv4.ignore-auto-dns yes'
    - 'nmcli conn modify "{{ idm_nmcli_interface_name }}" ipv4.dns  "{{ idm_server_ip_address }}"'

- name: Restart Network Connection
  service:
    name: NetworkManager
    state: restarted