---
dependency:
  name: galaxy
ansible:
  config_file: ../ansible.cfg
driver:
  name: docker
platforms:
  - name: instance
    image: part2-install-idm-image
    hostname: idm.example.com
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      vault_password_file: ${MOLECULE_PROJECT_DIRECTORY}/vault_secret
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - create
    - prepare
    - converge
    - verify
    - destroy
