---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      yum:
        name: "{{ item }}"
        use_backend: "dnf"
      with_items:
        - python3
        - python3-pip
    - name: Install Ansible
      command: "pip3 install ansible==2.9"
