---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Run setup
      setup:
      register: output_setup
    - name: Print setup
      debug:
        var: output_setup

    - name: Install this only for local dev machine
      debug:
        msg: "Your hostname is correctly set to '{{ ansible_fqdn }}'."
      when: ansible_fqdn == "idm.example5605.com"

    - name: You did not set the host name
      fail:
        msg:  "Your host name is '{{ ansible_fqdn }}' and should be 'idm.example5605.com'"
      when: ansible_fqdn != "idm.example5605.com"