---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Run setup
      setup:
      register: output_setup
    - name: Print setup
      debug:
        var: output_setup

    - name: Install this only for local dev machine
      debug:
        msg: "Your hostname is correctly set to '{{ ansible_fqdn }}'."
      when: ansible_fqdn == "idm.example2020.com"

    - name: You did not set the host name
      fail:
        msg:  "Your host name is '{{ ansible_fqdn }}' and should be 'idm.example2020.com'"
      when: ansible_fqdn != "idm.example2020.com"

    - name: collect facts about system services
      service_facts:
      register: services_state

    - name:  Determine if firewalld exists
      include_tasks: tasks/add-firewalld.yml