---
- name: Install the Required Libraries
  yum:
    name: "{{ item.name }}"
    state: present
    use_backend: "{{ yum_backend }}"
  with_items: "{{ yum_installs }}"

- name: Install Firewalld Service
  yum:
    name: firewalld
    state: present

- name:  Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes