- name: Register variable for open ports
  command:  firewall-cmd --list-ports
  register: open_ports

- name: Fail if an IDM Port is Closed
  fail:
    msg: "The port '{{ item }}' is not open."
  with_items: "{{ open_idm_ports }}"
  when: "'{{ item }}' not in open_ports.stdout"