---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Include the module vars file.
      include_vars:
        file: ../../defaults/main.yml

    - name:  Determine if vpc exists
      include_tasks: tasks/check-for-vpc-existence.yml

    - name:  Determine if vpc subnets exist
      include_tasks: tasks/check-for-vpc-subnet-existence.yml

    - name:  Determine if vpc gateway exists
      include_tasks: tasks/check-for-vpc-gateway-existence.yml

    - name:  Determine if route table exists
      include_tasks: tasks/check-for-vpc-route_table-existence.yml

    - name:  Determine if the security group exists
      include_tasks: tasks/check-for-vpc-security-group-existence.yml