- name: Get EC2 instance information
  ec2_instance_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ current_ec2_instance }}"
  register: ec2_info

- name: Populate Instance Id
  set_fact:
    ec2_instance_ids: "{{ ec2_instance_ids + [item_to_get_id_for.instance_id] }}"
  with_items: "{{ ec2_info.instances }}"
  loop_control:
    loop_var: item_to_get_id_for
  when:
    - ec2_info is defined
    - ec2_info.instances is defined
    - ec2_info.instances | length > 0
    - item_to_get_id_for.state.name != 'terminated'