---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: idm-client
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_user: centos
      vault_password_file: ${MOLECULE_PROJECT_DIRECTORY}/vault_secret
    privileged_escalation:
      become: true
      become_ask_pass: false
verifier:
  name: ansible
