---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: nexus-server
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_user: centos
    privileged_escalation:
      become: true
      become_ask_pass: false
verifier:
  name: ansible
  scenario:
    test_sequence:
      - dependency
      - lint
      - cleanup
      - destroy
      - syntax
      - create
      - prepare
      - converge
      - side_effect
      - verify
      - cleanup
      - destroy