# Single instance with ssd gp2 root volume
- name: Create EC2 Instance
  ec2:
    key_name: "{{ item.key_name }}"
    group: "{{ aws_vpc.security_group }}"
    instance_type: "{{ item.instance_type }}"
    image: "{{ item.ami }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    wait: true
    wait_timeout: 500
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ item.root_volume_size }}"
        delete_on_termination: true
    vpc_subnet_id: "{{ vpc_control_subnet.id }}"
    assign_public_ip: true
    count_tag:
      Name: "{{ item.name }}"
    instance_tags:
      Name: "{{ item.name }}"
    exact_count: 1
  with_items: "{{ ec2_instances }}"
  when: item.action == "create"
  register: ec2_facts