- name: Get EC2 instance information
  ec2_instance_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ current_ec2_instance }}"
  register: ec2_info

- name: Print instance info
  debug:
    var: ec2_info

- name: Delete EC2 Instance
  ec2:
    instance_ids: "{{ [item_to_delete.instance_id] }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    state: absent
    wait: yes
  with_items: "{{ ec2_info.instances }}"
  loop_control:
    loop_var: item_to_delete
  when:  ec2_info.instances is defined and ec2_info.instances | length > 0