- name: Get EC2 instance information
  ec2_instance_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ current_ec2_instance }}"
  register: ec2_info

- name: Start EC2 Instance
  ec2:
    instance_ids: "{{ [item_to_start.instance_id] }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    state: running
    wait: yes
  with_items: "{{ ec2_info.instances }}"
  loop_control:
    loop_var: item_to_start
  when:  ec2_info.instances is defined and ec2_info.instances | length > 0 and item_to_start.state.name != 'terminated'